### ISSUE TITLE
Get FEC set up with cloud.gov

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-transition#20] opened 2016-11-22 17:25 UTC
We need to conduct a training with members of the FEC integration team to get them set up with cloud.gov. The goal of this is to introduce them to the technology and get them set up with prototype environments so they can start to get comfortable.

This training should address things like the administrative commands and include a tutorial around deployment. 

As part of this, we may also want to develop a separate set of credentials.

**Comment by adrianwebb** [comment] 2016-12-20 04:51
Duplicate of: https://github.com/18F/fec-transition/issues/31

**Closed by adrianwebb** 2016-12-20 04:51 UTC
